// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID               uuid.UUID
	TitleApplication string
	Company          string
	SentDate         time.Time
	Status           string
	Notes            string
	UrlApplication   string
	UserID           uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Reminder struct {
	ID            uuid.UUID
	ReminderDate  time.Time
	Status        string
	ApplicationID uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
