// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID               int32
	TitleApplication string
	Company          string
	SentDate         pgtype.Date
	Status           pgtype.Text
	Notes            pgtype.Text
	UrlApplication   pgtype.Text
	UserID           int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Reminder struct {
	ID            int32
	ReminderDate  pgtype.Date
	Status        pgtype.Text
	ApplicationID int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
