// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID               uuid.UUID
	TitleApplication string
	Company          string
	Location         string
	SentDate         time.Time
	Status           pgtype.Text
	Notes            pgtype.Text
	UrlApplication   pgtype.Text
	UserID           uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Reminder struct {
	ID            uuid.UUID
	ReminderDate  time.Time
	Status        pgtype.Text
	ApplicationID uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Round struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Title         string
	Type          string
	Status        string
	Date          time.Time
	Notes         pgtype.Text
	Interviewer   pgtype.Text
	Duration      pgtype.Text
	Outcome       pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
