// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOneApplication = `-- name: CreateOneApplication :one
INSERT INTO
applications ( title_application, company, location, sent_date, status, notes, url_application, user_id ) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title_application, company, location, sent_date, status, notes, url_application, user_id, created_at, updated_at
`

type CreateOneApplicationParams struct {
	TitleApplication string
	Company          string
	Location         string
	SentDate         time.Time
	Status           string
	Notes            string
	UrlApplication   string
	UserID           uuid.UUID
}

func (q *Queries) CreateOneApplication(ctx context.Context, arg CreateOneApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createOneApplication,
		arg.TitleApplication,
		arg.Company,
		arg.Location,
		arg.SentDate,
		arg.Status,
		arg.Notes,
		arg.UrlApplication,
		arg.UserID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TitleApplication,
		&i.Company,
		&i.Location,
		&i.SentDate,
		&i.Status,
		&i.Notes,
		&i.UrlApplication,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users ( email, password ) VALUES ($1, $2) RETURNING id, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOneApplicationByID = `-- name: DeleteOneApplicationByID :exec
DELETE FROM applications WHERE id = $1 AND user_id = $2
`

type DeleteOneApplicationByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteOneApplicationByID(ctx context.Context, arg DeleteOneApplicationByIDParams) error {
	_, err := q.db.Exec(ctx, deleteOneApplicationByID, arg.ID, arg.UserID)
	return err
}

const getAllApplications = `-- name: GetAllApplications :many
SELECT id, title_application, company, location, sent_date, status, notes, url_application, user_id, created_at, updated_at FROM applications WHERE user_id = $1
`

func (q *Queries) GetAllApplications(ctx context.Context, userID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, getAllApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.TitleApplication,
			&i.Company,
			&i.Location,
			&i.SentDate,
			&i.Status,
			&i.Notes,
			&i.UrlApplication,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, password, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsCompanies = `-- name: GetAnalyticsCompanies :many
SELECT 
    company as name,
    COUNT(*) as applications,
    CAST(ROUND(
        CAST((COUNT(*) FILTER (WHERE status = 'pending')::float / 
         NULLIF(COUNT(*), 0)) * 100 AS numeric), 2
    ) AS float) as success_rate
FROM applications 
WHERE user_id = $1
GROUP BY company 
ORDER BY applications DESC 
LIMIT 10
`

type GetAnalyticsCompaniesRow struct {
	Name         string
	Applications int64
	SuccessRate  float64
}

func (q *Queries) GetAnalyticsCompanies(ctx context.Context, userID uuid.UUID) ([]GetAnalyticsCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsCompanies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalyticsCompaniesRow
	for rows.Next() {
		var i GetAnalyticsCompaniesRow
		if err := rows.Scan(&i.Name, &i.Applications, &i.SuccessRate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsOverview = `-- name: GetAnalyticsOverview :one
SELECT 
    COUNT(*) as total_applications,
    CAST(ROUND(
        CAST((COUNT(*) FILTER (WHERE status = 'pending')::float / 
         NULLIF(COUNT(*), 0)) * 100 AS numeric), 2
    ) AS float) as success_rate,
    COUNT(*) FILTER (WHERE sent_date >= CURRENT_DATE - INTERVAL '7 days') as applications_this_week
FROM applications 
WHERE user_id = $1
`

type GetAnalyticsOverviewRow struct {
	TotalApplications    int64
	SuccessRate          float64
	ApplicationsThisWeek int64
}

func (q *Queries) GetAnalyticsOverview(ctx context.Context, userID uuid.UUID) (GetAnalyticsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsOverview, userID)
	var i GetAnalyticsOverviewRow
	err := row.Scan(&i.TotalApplications, &i.SuccessRate, &i.ApplicationsThisWeek)
	return i, err
}

const getAnalyticsTrends = `-- name: GetAnalyticsTrends :many
SELECT 
    sent_date::text as date,
    COUNT(*) as count
FROM applications 
WHERE user_id = $1 
    AND sent_date >= $2 
    AND sent_date <= $3
GROUP BY sent_date 
ORDER BY sent_date
`

type GetAnalyticsTrendsParams struct {
	UserID     uuid.UUID
	SentDate   time.Time
	SentDate_2 time.Time
}

type GetAnalyticsTrendsRow struct {
	Date  string
	Count int64
}

func (q *Queries) GetAnalyticsTrends(ctx context.Context, arg GetAnalyticsTrendsParams) ([]GetAnalyticsTrendsRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsTrends, arg.UserID, arg.SentDate, arg.SentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalyticsTrendsRow
	for rows.Next() {
		var i GetAnalyticsTrendsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationCountsByUser = `-- name: GetApplicationCountsByUser :one
SELECT 
    COUNT(*) as total_count,
    COUNT(*) FILTER (WHERE status = 'sent') as sent_count,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'rejected') as rejected_count
FROM applications 
WHERE user_id = $1
`

type GetApplicationCountsByUserRow struct {
	TotalCount    int64
	SentCount     int64
	PendingCount  int64
	RejectedCount int64
}

func (q *Queries) GetApplicationCountsByUser(ctx context.Context, userID uuid.UUID) (GetApplicationCountsByUserRow, error) {
	row := q.db.QueryRow(ctx, getApplicationCountsByUser, userID)
	var i GetApplicationCountsByUserRow
	err := row.Scan(
		&i.TotalCount,
		&i.SentCount,
		&i.PendingCount,
		&i.RejectedCount,
	)
	return i, err
}

const getApplicationsByStatus = `-- name: GetApplicationsByStatus :many
SELECT id, title_application, company, location, sent_date, status, notes, url_application, user_id, created_at, updated_at FROM applications WHERE status = $1 AND user_id = $2 ORDER BY updated_at DESC, created_at DESC
`

type GetApplicationsByStatusParams struct {
	Status string
	UserID uuid.UUID
}

func (q *Queries) GetApplicationsByStatus(ctx context.Context, arg GetApplicationsByStatusParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, getApplicationsByStatus, arg.Status, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.TitleApplication,
			&i.Company,
			&i.Location,
			&i.SentDate,
			&i.Status,
			&i.Notes,
			&i.UrlApplication,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationsCount = `-- name: GetApplicationsCount :one
SELECT COUNT(*) FROM applications WHERE user_id = $1
`

func (q *Queries) GetApplicationsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getApplicationsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApplicationsCountByStatus = `-- name: GetApplicationsCountByStatus :one
SELECT COUNT(*) FROM applications WHERE user_id = $1 AND status = $2
`

type GetApplicationsCountByStatusParams struct {
	UserID uuid.UUID
	Status string
}

func (q *Queries) GetApplicationsCountByStatus(ctx context.Context, arg GetApplicationsCountByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, getApplicationsCountByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOneApplicationByID = `-- name: GetOneApplicationByID :one
SELECT id, title_application, company, location, sent_date, status, notes, url_application, user_id, created_at, updated_at FROM applications WHERE id = $1 AND user_id = $2
`

type GetOneApplicationByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOneApplicationByID(ctx context.Context, arg GetOneApplicationByIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, getOneApplicationByID, arg.ID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TitleApplication,
		&i.Company,
		&i.Location,
		&i.SentDate,
		&i.Status,
		&i.Notes,
		&i.UrlApplication,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOneUserByEmail = `-- name: GetOneUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetOneUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getOneUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOneUserByID = `-- name: GetOneUserByID :one
SELECT id, email, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetOneUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getOneUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopCompanyByUser = `-- name: GetTopCompanyByUser :one
SELECT company
FROM applications 
WHERE user_id = $1
GROUP BY company 
ORDER BY COUNT(*) DESC 
LIMIT 1
`

func (q *Queries) GetTopCompanyByUser(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTopCompanyByUser, userID)
	var company string
	err := row.Scan(&company)
	return company, err
}

const updateOneApplicationByID = `-- name: UpdateOneApplicationByID :one
UPDATE applications SET title_application = $1, company = $2, location = $3, sent_date = $4, status = $5, notes = $6, url_application = $7 WHERE id = $8 AND user_id = $9 RETURNING id, title_application, company, location, sent_date, status, notes, url_application, user_id, created_at, updated_at
`

type UpdateOneApplicationByIDParams struct {
	TitleApplication string
	Company          string
	Location         string
	SentDate         time.Time
	Status           string
	Notes            string
	UrlApplication   string
	ID               uuid.UUID
	UserID           uuid.UUID
}

func (q *Queries) UpdateOneApplicationByID(ctx context.Context, arg UpdateOneApplicationByIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateOneApplicationByID,
		arg.TitleApplication,
		arg.Company,
		arg.Location,
		arg.SentDate,
		arg.Status,
		arg.Notes,
		arg.UrlApplication,
		arg.ID,
		arg.UserID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.TitleApplication,
		&i.Company,
		&i.Location,
		&i.SentDate,
		&i.Status,
		&i.Notes,
		&i.UrlApplication,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
